# Generated by Django 6.0.6 on 2026-06-23 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0002_pais_alter_estudiante_id_alter_numerotelefonico_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pais',
            old_name='número_habitantes',
            new_name='numero_habitantes',
        ),
    ]
